### ISSUE TITLE
Variables in Documentation don't match deployment requirements

### ISSUE THREAD

**Issue by Jtango18** [liatrio/terraform-azure-github-runner#73]
**Describe the bug**
`azure_gallery_image_type` is listed as an optional parameter, but is rejected by Terraform during `apply`

**To Reproduce**
1. Create a basic `tf.main`
2. Add the `gitHub-runner` per standard documentation
3. Specify `azure_gallery_image_type` and supply a value
4. run `terraform apply`
5. Error is raised `Error: Unsupported argument`

**Expected behavior**
Terraform should apply successfully

**Desktop (please complete the following information):**
 - Version 0.1.0

**Comment by mitchell-liatrio** [comment]
Hey @Jtango18, 

Thanks for bringing this up.  We recently updated the variables.tf to have default values but I failed to publish a new release.  This should be resolved for you on 0.1.1

I'll close this issue now but please re-open if the issue persists.
