### ISSUE TITLE
azure_gallery_name is expected by module, but not documented anywhere.

### ISSUE THREAD

**Issue by Jtango18** [liatrio/terraform-azure-github-runner#74]
**Describe the bug**
`azure_gallery_name` is not described anywhere, but is an expected parameter.

**To Reproduce**
1. Create a basic `tf.main`
2. Add the `gitHub-runner` per standard documentation
4. run `terraform apply`
5. Error is raised `Error: Missing required argument`

**Expected behavior**
Terraform should apply successfully

**Desktop (please complete the following information):**
 - Version 0.1.0

**Comment by harsha-chamarthi** [comment]
I had the same error too...to resolve it i created a vm image in azure gallery in my azure account and passed it to the main.tf to resolve this.

**Comment by mitchell-liatrio** [comment]
Hey @Jtango18, 

Thanks for bringing this up.  We recently updated the variables.tf to have default values but I failed to publish a new release.  This should be resolved for you on 0.1.1

I'll close this issue now but please re-open if the issue persists.
