### ISSUE TITLE
Issue with Github App authentication 

### ISSUE THREAD

**Issue by harsha-chamarthi** [liatrio/terraform-azure-github-runner#77]
Hi,
After the deployment the runner-controller keeps crashing and i see the below error in the application logs,
```
2023-04-18T14:44:00.998587109Z RequestError [HttpError]: A JSON web token could not be decoded
2023-04-18T14:44:00.998592309Z     at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:88:21
2023-04-18T14:44:00.998597409Z     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-04-18T14:44:00.998602409Z     at async getInstallationAuthentication (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:190:7)
2023-04-18T14:44:00.998607309Z     at async hook (/usr/src/app/node_modules/@octokit/auth-app/dist-node/index.js:359:7)
2023-04-18T14:44:00.998612209Z     at async listGitHubRunners (file:///usr/src/app/github.js:54:22)
2023-04-18T14:44:00.998617110Z     at async listIdleGitHubRunners (file:///usr/src/app/github.js:63:21)
2023-04-18T14:44:00.998622010Z     at async Promise.all (index 0)
2023-04-18T14:44:00.998626910Z     at async getInitialRunnerWarmPool (file:///usr/src/app/runner/index.js:186:45)
2023-04-18T14:44:00.998631710Z     at async Promise.all (index 0)
2023-04-18T14:44:00.998658510Z     at async initializeRunnerState (file:///usr/src/app/runner/state.js:7:37) {
2023-04-18T14:44:00.998666310Z   status: 401,
```
Do i need to provide any additional permissions other then the below, <h4 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 16px; font-weight: var(--base-text-weight-semibold, 600); line-height: 1.25; color: rgb(201, 209, 217); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><strong style="box-sizing: border-box; font-weight: var(--base-text-weight-semibold, 600);">Permissions for GitHub App</strong></h4>

Permission | Access
-- | --
Repository: Actions | Read-only
Repository: Checks | Read-only
Repository: Metadata | Read-only
Organization: Self-hosted runners | Read and write

Also, in the pre-requisites it says  we need a GitHub App for Organization with owner access is this also required? I could not provide owner access to the github while configuring it. Please help.

**Comment by mitchell-liatrio** [comment]
Hi @harsha-chamarthi,we want to confirm a couple of items on this issue.

- Is the GitHub App installed to the organization?
- Have you uploaded all the secrets to KeyVault via the CLI?

**Comment by harsha-chamarthi** [comment]
Is the GitHub App installed to the organization? - Yes
Have you uploaded all the secrets to KeyVault via the CLI? - Yes, i have uploaded the private key using CLI

**Comment by mitchell-liatrio** [comment]
Okay, if it's installed at the organization and has the permission outlined above, it should have access and shouldn't be receiving a 401 error.  

If it's okay with you, we may set up a call and have a short troubleshooting session.  Mind sending me an email at mitchellp@liatrio.com and we can find a time to sync up?

**Comment by harsha-chamarthi** [comment]
@mitchell-liatrio I have a created a new private key and added to github app, hope that has resolved the issue. However i am getting different error now,

`2023-04-20T12:56:17.193089150Z {"level":30,"time":1681995377188,"pid":1,"hostname":"432a57b60f8c","runnerName":"runner-35998414","msg":"Received runner on queue"}2023-04-20T12:56:19.436265123Z {"level":50,"time":1681995379427,"pid":1,"hostname":"432a57b60f8c","err":{"type":"RestError","message":"","stack":"RestError\n at handleErrorResponse (/usr/src/app/node_modules/@azure/core-http/dist/index.js:3159:19)\n at /usr/src/app/node_modules/@azure/core-http/dist/index.js:3095:49\n at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","name":"RestError","statusCode":404,"request":{"streamResponseStatusCodes":{},"url":"https://appcs-gh-run-controller-ghrdevsea.azconfig.io/kv/azure-gallery-image-type?api-version=1.0",`

azure-gallery-image-type this variable seems to be added in the latest release 0.1.1, but when i try to upgrade to the latest release. I am getting error as mentioned in the issue, https://github.com/liatrio/terraform-azure-github-runner/issues/78

**Comment by harsha-chamarthi** [comment]
Closing the issue as the error was resolved after recreating the keyvautl
