### ISSUE TITLE
Runner VM Deletion in Azure After Completion of Job execution

### ISSUE THREAD

**Issue by harsha-chamarthi** [liatrio/terraform-azure-github-runner#80]
Hi Team,
I was able to deploy the solution and register the runners to my gihub org. However, after the job execution completes in ephemeral mode, the github runner unregisters from my org but the runner VM still exists in Azure. Is the deletion of runners implemented as part of the runner setup or the runner-controller?

**Comment by mitchell-liatrio** [comment]
Hey @harsha-chamarthi, they should be getting deleted by the runner-controller.  Let me take a look at this later and follow up with you.  Other than that potential bug, is everyone else working as expected?

**Comment by harsha-chamarthi** [comment]
@mitchell-liatrio Is there any update on this? Everything else seems to be working as expected, except the deletion of runners. Because the VM's are not being deleted after job execution, the runner-controller thinks there are active runners and does not create new ones when requested.

**Comment by harsha-chamarthi** [comment]
@mitchell-liatrio Please ignore. I found the issue was with my webhook url. So closing this issue, will let u know if i face any other issues.
